"""All 25 curated Corporate Bathroom Chronicles stories."""

STORIES = [
    # 1
    (
        "I'll never forget the moment that changed my career.\n"
        "\n"
        "It was Q3 2019. I was mid-presentation to the entire C-suite when my "
        "stomach made a sound that I can only describe as \"demonic gargling.\"\n"
        "\n"
        "I had 14 slides left.\n"
        "\n"
        "I excused myself. I walked \u2014 not ran \u2014 to the nearest restroom. "
        "It was occupied. I walked to the next floor. Also occupied.\n"
        "\n"
        "I ended up in the basement utility bathroom next to the server room. "
        "There was no lock on the door. I held it shut with my foot while my "
        "body performed an exorcism.\n"
        "\n"
        "I returned 22 minutes later. Nobody said a word. I finished the "
        "presentation. We closed the deal.\n"
        "\n"
        "That quarter I was promoted.\n"
        "\n"
        "Nobody talks about the resilience it takes to clench through a board "
        "presentation. But I will.\n"
        "\n"
        "#Leadership #Resilience #CorporateLife"
    ),

    # 2
    (
        "A few years ago, I was flown to Tokyo for a client meeting. "
        "$40K deal on the line.\n"
        "\n"
        "The night before, I ate something from a street vendor near Shibuya. "
        "I won't go into detail, but by 6 AM I had a relationship with my "
        "hotel bathroom that I can only describe as \"committed.\"\n"
        "\n"
        "The meeting was at 9. I wore my best suit. I took 4 Imodium. "
        "I smiled through the handshake.\n"
        "\n"
        "At 9:47 AM, mid-negotiation, I felt The Rumble.\n"
        "\n"
        "I bowed. Said \"sumimasen.\" Found a bathroom 3 floors down. "
        "The toilet was heated. It had buttons I didn't understand. "
        "I pressed one. Water shot upward. I screamed.\n"
        "\n"
        "I came back. Closed the deal. Got a $12K bonus.\n"
        "\n"
        "The lesson? Your body will betray you. But your mindset never has to.\n"
        "\n"
        "Disagree? \U0001f447"
    ),

    # 3
    (
        "I'm going to say something controversial.\n"
        "\n"
        "I think your relationship with the office bathroom says more about "
        "your leadership style than any 360 review ever will.\n"
        "\n"
        "I once had a VP who would take 45-minute bathroom breaks with the "
        "Wall Street Journal tucked under his arm. He didn't care who saw. "
        "He made $430K a year.\n"
        "\n"
        "Meanwhile, I watched a junior analyst hold it in for an entire "
        "3-hour strategy session because she was afraid to excuse herself. "
        "She got laid off 4 months later.\n"
        "\n"
        "Coincidence? Maybe.\n"
        "\n"
        "But I've been in corporate America for 16 years, and I've noticed "
        "a pattern: the people who are unapologetic about their bathroom "
        "needs are the same people who are unapologetic about asking for "
        "raises, pushing back on bad ideas, and setting boundaries.\n"
        "\n"
        "Take from that what you will.\n"
        "\n"
        "\U0001f9f5 Thread on bathroom confidence and executive presence "
        "coming tomorrow."
    ),

    # 4
    (
        "True story.\n"
        "\n"
        "My first week as a McKinsey associate, I clogged the toilet on "
        "the 31st floor. The PARTNER floor.\n"
        "\n"
        "There was no plunger. I looked for one. There was no plunger on "
        "the entire floor. These people had apparently never encountered "
        "resistance.\n"
        "\n"
        "I took the elevator down to 28. Borrowed a plunger from the "
        "janitor's closet. Rode back up. A senior partner got in on 30.\n"
        "\n"
        "We made small talk about the Nasdaq while I held a plunger "
        "behind my back.\n"
        "\n"
        "I fixed the situation. Returned the plunger. Never spoke of it "
        "again.\n"
        "\n"
        "That partner later became my mentor. I sometimes wonder if he "
        "smelled what I had done. If he did, he never mentioned it.\n"
        "\n"
        "That's what real professionalism looks like."
    ),

    # 5
    (
        "Last week an intern asked me what the most important career "
        "advice I've ever received was.\n"
        "\n"
        "I told him the truth.\n"
        "\n"
        "In 2014, my manager pulled me aside after a team lunch at "
        "Chipotle. He looked me in the eye and said: \"Never trust a "
        "fart during earnings season.\"\n"
        "\n"
        "I laughed. He didn't.\n"
        "\n"
        "He was dead serious. And you know what? He was right. The "
        "pressure, the late nights, the catered Panera \u2014 your GI tract "
        "is operating in a wartime environment during Q4 close.\n"
        "\n"
        "I've seen directors lose composure. I've seen VPs make The Walk "
        "of Shame to the far bathroom. I once saw a CFO excuse himself "
        "from an all-hands and not return for 40 minutes.\n"
        "\n"
        "Nobody teaches you this in business school. But it's the most "
        "honest career advice I can give.\n"
        "\n"
        "Take care of your gut. Your career depends on it."
    ),

    # 6
    (
        "I need to talk about something nobody in corporate America "
        "wants to acknowledge.\n"
        "\n"
        "The post-lunch meeting.\n"
        "\n"
        "You know the one. 1:30 PM. Conference room B. Fourteen people. "
        "Catered Mexican from that place on 5th.\n"
        "\n"
        "By 2:15, the room is silent but the stomachs are not. You can "
        "hear a symphony of biological processes happening in real time. "
        "Nobody makes eye contact.\n"
        "\n"
        "At 2:22, Dave from accounting stands up. He doesn't say where "
        "he's going. He doesn't need to. We all know. We've all been "
        "doing the math on when we can leave too.\n"
        "\n"
        "Dave comes back 11 minutes later looking like a man reborn. "
        "The rest of us suffer in silence for another 35 minutes.\n"
        "\n"
        "Be like Dave. Dave made VP last year.\n"
        "\n"
        "The correlation between bathroom courage and career advancement "
        "is something Harvard Business Review is too afraid to study.\n"
        "\n"
        "#CorporateCourage #BeMoreDave"
    ),

    # 7
    (
        "In 2017, I was in the middle of a company-wide town hall. "
        "400 people. CEO on stage.\n"
        "\n"
        "I was in row 3. A seat I had fought for. Visibility matters "
        "when you're gunning for director.\n"
        "\n"
        "Then, without warning, my body issued a non-negotiable demand.\n"
        "\n"
        "I had two choices: stay in row 3 and risk a career-ending "
        "incident, or stand up in front of 400 colleagues and the CEO "
        "mid-sentence.\n"
        "\n"
        "I stood up. I walked out. The CEO paused. I felt 400 pairs of "
        "eyes on my back.\n"
        "\n"
        "I made it to the bathroom with approximately 4 seconds to spare. "
        "I will not elaborate on what happened next, but I will say this: "
        "the bathroom had an echo.\n"
        "\n"
        "I returned to the town hall 18 minutes later and sat in the "
        "back row. The CEO had moved on. Nobody said anything.\n"
        "\n"
        "I got the director promotion 3 months later.\n"
        "\n"
        "The lesson: sometimes you have to leave the room to stay in "
        "the game."
    ),

    # 8
    (
        "Unpopular opinion: the single-stall bathroom on the 4th floor "
        "that nobody knows about is worth more than any corner office.\n"
        "\n"
        "Every company has one. The secret bathroom. The one tucked "
        "behind the old supply closet near the freight elevator.\n"
        "\n"
        "I found mine during my second week at Deloitte. I was desperate. "
        "The main restrooms were a warzone \u2014 three stalls, twelve "
        "consultants, one dream.\n"
        "\n"
        "I wandered. I explored. And there it was. Single occupancy. "
        "A lock that worked. A fan that actually moved air. A window.\n"
        "\n"
        "For 3 years, that bathroom was my sanctuary. My competitive "
        "advantage. While others waited in line, I was at peace.\n"
        "\n"
        "Then Kyle from Strategy found it. He told people. It was over.\n"
        "\n"
        "I left the firm 6 months later. Not entirely because of the "
        "bathroom. But not NOT because of the bathroom.\n"
        "\n"
        "Protect your secret bathroom. Trust no one. Especially Kyle."
    ),

    # 9
    (
        "The year was 2021. I was on a Zoom call with a Fortune 500 "
        "client. $2.3M contract renewal.\n"
        "\n"
        "I was working from home. Casual Friday. No pants. You know "
        "the drill.\n"
        "\n"
        "At minute 34, my body made a decision that my mind did not "
        "approve of.\n"
        "\n"
        "I muted myself. Turned off video. Said \"sorry, connection "
        "issues.\" Sprinted to the bathroom.\n"
        "\n"
        "What I did not realize is that my Bluetooth headset was still "
        "connected. And my mic was not, in fact, muted.\n"
        "\n"
        "I learned this when I returned to find a Slack message from "
        "my manager that simply said: \"Your mic.\"\n"
        "\n"
        "The client renewed the contract anyway. We never discussed it.\n"
        "\n"
        "Some relationships are built on trust. Others are built on "
        "mutually agreed-upon silence.\n"
        "\n"
        "That's business."
    ),

    # 10
    (
        "A recruiter DMed me last month asking what my \"non-negotiables\" "
        "are when evaluating a new role.\n"
        "\n"
        "I gave the standard answers. Comp. Culture. Growth opportunities.\n"
        "\n"
        "But the real answer? The one I didn't say?\n"
        "\n"
        "Bathroom quality.\n"
        "\n"
        "I have turned down two offers in my career because of the "
        "restroom situation. One had shared bathrooms with a WeWork "
        "floor. The other had exactly one stall for 200 employees.\n"
        "\n"
        "I once accepted a role 15% below market rate because the "
        "office had private, soundproofed bathrooms with premium "
        "toilet paper and ambient lighting.\n"
        "\n"
        "I stayed at that company for 5 years. Best decision I ever made.\n"
        "\n"
        "You can negotiate salary. You can negotiate PTO. But you "
        "cannot negotiate plumbing.\n"
        "\n"
        "HR won't tell you this. But I will.\n"
        "\n"
        "#CareerAdvice #TheRealNonNegotiables"
    ),

    # 11
    (
        "I want to talk about something that happened to me at "
        "Salesforce Dreamforce 2018.\n"
        "\n"
        "22,000 people. One convention center. Not enough bathrooms.\n"
        "\n"
        "I had just eaten a sponsored breakfast burrito. The kind "
        "that comes in a branded wrapper and makes promises it "
        "cannot keep.\n"
        "\n"
        "By the keynote, I was sweating. Not from inspiration. "
        "From biology.\n"
        "\n"
        "The nearest bathroom had a line out the door. I walked "
        "past it. Then the next one. Same thing. I was now speed-"
        "walking through a crowd of people in Salesforce hoodies "
        "like a man being chased.\n"
        "\n"
        "I found a bathroom in a restricted area behind the expo "
        "hall. I told the security guard I was a speaker. I was not "
        "a speaker. He let me in anyway. I think he could see the "
        "urgency in my eyes.\n"
        "\n"
        "That bathroom was pristine. Empty. It had a couch. A COUCH.\n"
        "\n"
        "I networked more effectively from that bathroom than I did "
        "from any booth on the expo floor.\n"
        "\n"
        "Resourcefulness isn't taught. It's forged.\n"
        "\n"
        "#Dreamforce #Hustle"
    ),

    # 12
    (
        "My first business trip to India. Mumbai. 2016.\n"
        "\n"
        "My American stomach was not prepared.\n"
        "\n"
        "Day 2: I'm in a glass-walled conference room with 8 "
        "stakeholders. The office is open-plan. The bathroom is "
        "visible from the conference room. Glass walls everywhere. "
        "Very modern. Very transparent. Very bad for me.\n"
        "\n"
        "I excused myself. Walked to the bathroom. Everyone watched. "
        "The stall doors were frosted glass. FROSTED. You could see "
        "shapes. Silhouettes. Movement.\n"
        "\n"
        "I did what I had to do as quietly as humanly possible. "
        "It was not quiet.\n"
        "\n"
        "I returned to the conference room. Nobody acknowledged "
        "what had happened, even though architecturally, it was "
        "impossible not to.\n"
        "\n"
        "We closed a $780K deal that afternoon.\n"
        "\n"
        "There is no vulnerability greater than a glass bathroom "
        "in a foreign office. And there is no trust greater than "
        "the one built when your clients pretend they didn't see "
        "what they definitely saw.\n"
        "\n"
        "That's partnership."
    ),

    # 13
    (
        "A thread on something nobody talks about: Bathroom "
        "Power Dynamics.\n"
        "\n"
        "In every office, there is a hierarchy. And nowhere is "
        "it more visible than in who uses which bathroom and when.\n"
        "\n"
        "The CEO uses the executive bathroom. Single occupancy. "
        "Fresh flowers. We don't talk about it.\n"
        "\n"
        "The VPs use the 12th floor bathroom because it's always "
        "empty. They've silently agreed on this. No memo was sent.\n"
        "\n"
        "Middle management shares the 8th floor. Three stalls. "
        "Passive-aggressive courtesy flushes. An unspoken agreement "
        "about the spacing rule.\n"
        "\n"
        "The rest of us? The 3rd floor. Five stalls. No privacy. "
        "The soap dispenser has been empty since February.\n"
        "\n"
        "I once accidentally used the executive bathroom because "
        "I was on the wrong floor. It had heated seats. Warm water. "
        "A painting.\n"
        "\n"
        "I understood, in that moment, what I was really working "
        "toward.\n"
        "\n"
        "It's not the title. It's not the equity. It's the bathroom.\n"
        "\n"
        "And if you disagree, you've never sat on a heated seat."
    ),

    # 14
    (
        "I almost lost a $1.6M client because of a bathroom.\n"
        "\n"
        "We were hosting them at our office. Big pitch. Catered "
        "lunch. The works. I'm talking branded napkins.\n"
        "\n"
        "After lunch, the client's VP excused herself. She came "
        "back 3 minutes later and quietly said: \"Your women's "
        "restroom is out of toilet paper.\"\n"
        "\n"
        "The room went silent.\n"
        "\n"
        "I called facilities. No answer. I walked to the supply "
        "closet myself. Grabbed a 12-pack of toilet paper. Walked "
        "it through the open-plan office in front of 150 employees. "
        "Delivered it personally.\n"
        "\n"
        "The client watched me do this. She nodded.\n"
        "\n"
        "We won the account. In the debrief, she told our CEO that "
        "my \"bias toward action\" impressed her more than the pitch "
        "deck.\n"
        "\n"
        "She was talking about the toilet paper. We both knew it.\n"
        "\n"
        "Leadership is not about the big moments. It's about the "
        "toilet paper moments."
    ),

    # 15
    (
        "Hot take: Open-plan offices are a human rights violation, "
        "and I'll tell you exactly why.\n"
        "\n"
        "Not because of noise. Not because of distractions.\n"
        "\n"
        "Because everyone can see you walk to the bathroom.\n"
        "\n"
        "And everyone can time you.\n"
        "\n"
        "I worked at a startup in 2015 where my desk was 12 feet "
        "from the single bathroom. The ONLY bathroom. For 30 people.\n"
        "\n"
        "Every time someone went in, I could hear the lock click. "
        "Every time someone came out, I could see their face. The "
        "post-bathroom face. You know the one.\n"
        "\n"
        "People started timing each other. Not officially. But "
        "Jason in marketing once said \"took you a while\" to a "
        "senior engineer and she quit two weeks later.\n"
        "\n"
        "We lost a 10x engineer because of Jason and a bathroom.\n"
        "\n"
        "The company folded 8 months later.\n"
        "\n"
        "Causation? I can't prove it.\n"
        "\n"
        "But I know what I know."
    ),

    # 16
    (
        "The most important meeting of my career lasted 45 seconds.\n"
        "\n"
        "It was 2020. I was in the men's room on the 9th floor. "
        "Stall 3. My preferred stall. Doing what needed to be done.\n"
        "\n"
        "The door opened. Someone walked in. I recognized the shoes. "
        "$800 John Lobbs. Only one person in the building wore those.\n"
        "\n"
        "The CEO.\n"
        "\n"
        "He took the stall next to me. Stall 2. A bold choice.\n"
        "\n"
        "For approximately 45 seconds, we were just two men. No "
        "titles. No org chart. No pretense.\n"
        "\n"
        "As we washed our hands \u2014 side by side \u2014 he looked at me "
        "in the mirror and said: \"Good work on the Henderson deck.\"\n"
        "\n"
        "That was it. 45 seconds. A nod. An acknowledgment.\n"
        "\n"
        "I was promoted within the quarter.\n"
        "\n"
        "The bathroom is the great equalizer. Every CEO poops. "
        "Remember that the next time you're intimidated by "
        "someone's title.\n"
        "\n"
        "#Leadership #Perspective"
    ),

    # 17
    (
        "Something happened at our company retreat that I think "
        "about at least once a week.\n"
        "\n"
        "We were at a resort in Scottsdale. Team-building. Trust "
        "falls. The whole thing.\n"
        "\n"
        "The first night, the company bought dinner. Surf and turf. "
        "Open bar. Bad combination for 60 finance professionals.\n"
        "\n"
        "By 6 AM, there was a line for the lobby bathroom. Five "
        "directors. Two VPs. One managing director. All standing "
        "in bathrobes, trying to maintain dignity.\n"
        "\n"
        "The MD looked at me. I looked at the MD. We were both "
        "clenching.\n"
        "\n"
        "\"This,\" he said, \"is the real team building.\"\n"
        "\n"
        "He wasn't wrong. We bonded more in that lobby bathroom "
        "line than we did in any trust fall.\n"
        "\n"
        "Shared suffering creates shared trust. It's primal. "
        "It's biological. And it's more effective than any "
        "$50K team-building consultant.\n"
        "\n"
        "Save your budget. Just buy everyone bad seafood.\n"
        "\n"
        "#TeamBuilding #CorporateRetreat"
    ),

    # 18
    (
        "I need to address something I've been seeing on this app.\n"
        "\n"
        "People bragging about \"hustle culture\" and working "
        "18-hour days.\n"
        "\n"
        "Let me tell you what hustle culture actually looks like.\n"
        "\n"
        "It's 11 PM. You're still at the office. You've had "
        "nothing but cold Sweetgreen and vending machine coffee "
        "since noon. Your body is staging a revolution.\n"
        "\n"
        "You're on a call with Singapore. You can't leave. The "
        "client is talking about deliverables. Your intestines "
        "are talking about something else entirely.\n"
        "\n"
        "You mute yourself. You look at the bathroom. It's 40 "
        "feet away. The cleaning crew is in there. Of course they "
        "are. It's 11 PM.\n"
        "\n"
        "You wait. You clench. You take notes with one hand and "
        "grip the armrest with the other.\n"
        "\n"
        "The call ends at 11:47 PM. You run. The cleaning crew "
        "sees you coming and moves aside. They've seen this before.\n"
        "\n"
        "THAT is hustle. Not your morning routine threads.\n"
        "\n"
        "#HustleCulture #RealTalk"
    ),

    # 19
    (
        "3 things they don't tell you about business travel:\n"
        "\n"
        "1. Airport bathrooms are a competitive sport. You have "
        "7 minutes between boarding groups. You learn what you're "
        "made of in those 7 minutes.\n"
        "\n"
        "2. Hotel bathroom acoustics are a lie. That fan does "
        "nothing. Your colleague in the adjoining room heard "
        "everything at the Marriott in Charlotte. He just chose "
        "not to mention it. Professional courtesy.\n"
        "\n"
        "3. Never \u2014 and I mean NEVER \u2014 eat the conference lunch "
        "on Day 1. Day 1 is when you have the most important "
        "meetings. Day 1 is when you need to be operational.\n"
        "\n"
        "I've seen a director eat the salmon on Day 1 at a "
        "conference in Vegas. He missed the afternoon keynote. "
        "He missed a networking dinner. He missed, as far as "
        "I can tell, most of Tuesday.\n"
        "\n"
        "Travel is the ultimate test of gastrointestinal management. "
        "And gastrointestinal management is the ultimate test of "
        "character.\n"
        "\n"
        "Plan accordingly."
    ),

    # 20
    (
        "I interviewed at Google in 2019. The interview went great. "
        "Five rounds. Strong signals across the board.\n"
        "\n"
        "Between rounds 3 and 4, I asked for a bathroom break.\n"
        "\n"
        "They pointed me down a hallway. I walked. And walked. "
        "The Google campus is, as it turns out, enormous. I couldn't "
        "find the bathroom. I was lost. In Google.\n"
        "\n"
        "I asked someone. They said \"take the scooter.\" There was "
        "a scooter. I took the scooter. I scootered to a bathroom "
        "that was in what I believe was a different building.\n"
        "\n"
        "I was gone for 14 minutes. The interviewer asked if "
        "everything was okay. I said yes. Everything was not okay. "
        "But I couldn't tell a Google interviewer that I had gotten "
        "lost trying to find a toilet in their campus.\n"
        "\n"
        "I got the offer. I didn't take it. The bathroom situation "
        "was a factor.\n"
        "\n"
        "Some things matter more than RSUs."
    ),

    # 21
    (
        "Let me tell you about the worst day of my professional life.\n"
        "\n"
        "Client dinner. Michelin-starred restaurant. Manhattan. "
        "7 people. $4,800 tab. My treat, obviously. I was the "
        "vendor.\n"
        "\n"
        "The oysters were a mistake. I knew it by the appetizer "
        "course. By the main course, I was doing mental calculations "
        "about the nearest bathroom.\n"
        "\n"
        "I smiled. I ordered dessert for the table. I poured wine. "
        "I was, by all external measures, a consummate professional.\n"
        "\n"
        "Internally, I was negotiating with God.\n"
        "\n"
        "The check came. I signed it. I shook hands. I put them "
        "in cabs. I waited until every single one of them was gone.\n"
        "\n"
        "Then I walked \u2014 very carefully \u2014 to the restaurant bathroom. "
        "The hostess said it was for customers only. I showed her "
        "the $4,800 receipt. She let me in.\n"
        "\n"
        "I stayed for 35 minutes. The manager knocked twice.\n"
        "\n"
        "Nobody will ever know how close I came to losing that "
        "account. But I'll know. And that's enough.\n"
        "\n"
        "Composure is a skill. And I am elite."
    ),

    # 22
    (
        "People ask me what my morning routine is.\n"
        "\n"
        "They expect me to say meditation. Journaling. A 5 AM "
        "workout.\n"
        "\n"
        "Here's my actual morning routine:\n"
        "\n"
        "5:30 AM: Wake up.\n"
        "5:35 AM: Coffee.\n"
        "5:42 AM: The coffee does its job.\n"
        "5:43 - 6:15 AM: I am unavailable.\n"
        "6:15 AM: Shower. Dress. Ready for the day.\n"
        "\n"
        "That 33-minute window is the most important part of my "
        "morning. It's non-negotiable. I have rescheduled early "
        "meetings for it. I have missed flights for it. I once "
        "told a client I had a \"standing appointment\" from "
        "5:43 to 6:15 that could not be moved.\n"
        "\n"
        "They respected it. Because I said it with conviction.\n"
        "\n"
        "The most successful people I know have a morning bathroom "
        "routine that they protect with their lives. It sets the "
        "tone for the entire day.\n"
        "\n"
        "You can have a $3,000 morning routine with cold plunges "
        "and red light therapy. Or you can have coffee and 33 "
        "minutes.\n"
        "\n"
        "I know which one actually works."
    ),

    # 23
    (
        "True story. My colleague \u2014 let's call him Mike \u2014 was on a "
        "video call with a potential investor. Series B round. $18M "
        "on the line.\n"
        "\n"
        "Mid-pitch, his face changed. We all saw it. That subtle "
        "shift from confidence to crisis. The slight squirm. The "
        "jaw clench.\n"
        "\n"
        "He looked at the camera and said, with the composure of a "
        "man defusing a bomb: \"I'm going to switch to my phone for "
        "a moment. Please continue reviewing the deck.\"\n"
        "\n"
        "We heard a chair push back. Footsteps. A door close.\n"
        "\n"
        "Three minutes of silence.\n"
        "\n"
        "He returned. Shirt slightly untucked. But his voice was "
        "steady. He nailed the close.\n"
        "\n"
        "The investor committed $18M.\n"
        "\n"
        "After the call, I asked Mike what happened. He looked "
        "me dead in the eye and said: \"We never speak of this.\"\n"
        "\n"
        "We never did. Until now. Sorry Mike. But the world needs "
        "to know what real entrepreneurship looks like.\n"
        "\n"
        "#StartupLife #Founders #Resilience"
    ),

    # 24
    (
        "The single most underrated skill in corporate America?\n"
        "\n"
        "Strategic bathroom timing.\n"
        "\n"
        "Let me explain.\n"
        "\n"
        "Every office has rush hours. 10:15 AM (post-coffee). "
        "2:30 PM (post-lunch). 4:45 PM (the pre-commute clear-out).\n"
        "\n"
        "The amateurs go during rush hour. They wait in line. "
        "They share the space. They make small talk at the sink "
        "with people they'll later see in meetings. Horrifying.\n"
        "\n"
        "The professionals? We go at 11:40. The dead zone. "
        "Everyone's in meetings. The bathroom is empty. It's "
        "peaceful. You could do yoga in there.\n"
        "\n"
        "I once mapped out the bathroom traffic patterns in our "
        "office over a 3-week period. I used a spreadsheet. I "
        "identified optimal windows. I scheduled my calendar around "
        "them.\n"
        "\n"
        "My productivity went up 23%. My stress went down. My "
        "annual review said I had \"excellent time management.\"\n"
        "\n"
        "They had no idea.\n"
        "\n"
        "Work smarter, not harder. And that includes the bathroom.\n"
        "\n"
        "#Productivity #TimeManagement"
    ),

    # 25
    (
        "I'm retiring from corporate America next month. 22 years. "
        "4 companies. 2 continents. 1 lesson.\n"
        "\n"
        "Here it is.\n"
        "\n"
        "In 22 years, I've had hundreds of meetings, dozens of "
        "promotions, countless deals closed. But the moments I "
        "remember most? The bathroom moments.\n"
        "\n"
        "The time I ran out of a Goldman Sachs pitch to find a "
        "bathroom. The client waited. We closed.\n"
        "\n"
        "The time I discovered the secret bathroom on Floor 6 "
        "and didn't tell a soul for 4 years.\n"
        "\n"
        "The time I shook hands with a Fortune 100 CEO and went "
        "straight to the restroom because I'd been holding it "
        "for 2 hours and 47 minutes.\n"
        "\n"
        "The time my mentor told me: \"The people who pretend "
        "they don't poop are the same people who pretend the "
        "numbers look fine. Trust neither.\"\n"
        "\n"
        "He was right.\n"
        "\n"
        "Corporate America runs on pretense. But your body doesn't.\n"
        "\n"
        "Be honest. Be human. And for the love of God, go when "
        "you need to go.\n"
        "\n"
        "That's it. That's the post. That's 22 years of wisdom.\n"
        "\n"
        "Thank you for reading. I'll be in the bathroom.\n"
        "\n"
        "#Retirement #CorporateLife #Authenticity #Leadership"
    ),
]


def split_into_tweets(story: str, max_length: int = 280) -> list[str]:
    """Split a story into tweet-sized chunks at paragraph breaks."""
    paragraphs = story.split("\n\n")
    tweets = []
    current = ""

    for para in paragraphs:
        # If adding this paragraph would exceed the limit, start a new tweet
        if current and len(current + "\n\n" + para) > max_length:
            tweets.append(current.strip())
            current = para
        elif not current:
            current = para
        else:
            current += "\n\n" + para

    if current.strip():
        tweets.append(current.strip())

    return tweets
